const PlacesOfService = [
  { value: '01', title: '01 - Pharmacy' },
  { value: '02', title: '02 - Telehealth Provided Other than in Patient’s Home' },
  { value: '03', title: '03 - School' },
  { value: '04', title: '04 - Homeless Shelter' },
  { value: '05', title: '05 - Indian Health Service Free-standing Facility' },
  { value: '06', title: '06 - Indian Health Service Provider-based Facility' },
  { value: '07', title: '07 - Tribal 638 Free-standing Facility' },
  { value: '08', title: '08 - Tribal 638 Provider-based Facility' },
  { value: '09', title: '09 - Prison/Correctional Facility' },
  { value: '10', title: '10 - Telehealth Provided in Patient’s Home' },
  { value: '11', title: '11 - Office Location' },
  { value: '12', title: '12 - Home Location' },
  { value: '13', title: '13 - Assisted Living Facility' },
  { value: '14', title: '14 - Group Home' },
  { value: '15', title: '15 - Mobile Unit' },
  { value: '16', title: '16 - Temporary Lodging' },
  { value: '17', title: '17 - Walk-in Retail Health Clinic' },
  { value: '18', title: '18 - Place of Employment-Worksite' },
  { value: '19', title: '19 - Off Campus-Outpatient Hospital' },
  { value: '20', title: '20 - Urgent Care Facility Location' },
  { value: '21', title: '21 - Inpatient Hospital' },
  { value: '22', title: '22 - On Campus-Outpatient Hospital' },
  { value: '23', title: '23 - Emergency Room – Hospital' },
  { value: '24', title: '24 - Ambulatory Surgical Center' },
  { value: '25', title: '25 - Birthing Center' },
  { value: '26', title: '26 - Military Treatment Facility' },
  { value: '27', title: '27 - Outreach Site/ Street' },
  { value: '31', title: '31 - Skilled Nursing Facility' },
  { value: '32', title: '32 - Nursing Facility' },
  { value: '33', title: '33 - Custodial Care Facility' },
  { value: '34', title: '34 - Hospice' },
  { value: '41', title: '41 - Ambulance - Land' },
  { value: '42', title: '42 - Ambulance – Air or Water' },
  { value: '49', title: '49 - Independent Clinic' },
  { value: '50', title: '50 - Federally Qualified Health Center' },
  { value: '51', title: '51 - Inpatient Psychiatric Facility' },
  { value: '52', title: '52 - Psychiatric Facility-Partial Hospitalization' },
  { value: '53', title: '53 - Community Mental Health Center' },
  { value: '54', title: '54 - Intermediate Care Facility/ Individuals with Intellectual Disabilities' },
  { value: '55', title: '55 - Residential Substance Abuse Treatment Facility' },
  { value: '56', title: '56 - Psychiatric Residential Treatment Center' },
  { value: '57', title: '57 - Non-residential Substance Abuse Treatment Facility' },
  { value: '58', title: '58 - Non-residential Opioid Treatment Facility' },
  { value: '60', title: '60 - Mass Immunization Center' },
  { value: '61', title: '61 - Comprehensive Inpatient Rehabilitation Facility' },
  { value: '62', title: '62 - Comprehensive Outpatient Rehabilitation Facility' },
  { value: '65', title: '65 - End-Stage Renal Disease Treatment Facility' },
  { value: '71', title: '71 - Public Health Clinic' },
  { value: '72', title: '72 - Rural Health Clinic' },
  { value: '81', title: '81 - Independent Laboratory' },
  { value: '99', title: '99 - Other Place of Service' },
  { value: '00', title: '00 - Placeholder' },
]

export default PlacesOfService